# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "jsonui-unstable-${version}";
  version = "2018-09-15";
  rev = "66c25effcc5129fae51bea04badac17e0f291855";

  goPackagePath = "github.com/gulyasm/jsonui";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/gulyasm/jsonui";
    sha256 = "16c8qr57rwsa12cl1ixx2wcv3kynwriahn488cph6k49fhf5cdkd";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
