# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/jroimartin/gocui";
    fetch = {
      type = "git";
      url = "https://github.com/jroimartin/gocui";
      rev = "c055c87ae801372cd74a0839b972db4f7697ae5f";
      sha256 = "1b1cbjg925l1c5v3ls8amni9716190yzf847cqs9wjnj82z8qa47";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-runewidth";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-runewidth";
      rev = "703b5e6b11ae25aeb2af9ebb5d5fdf8fa2575211";
      sha256 = "0znpyz71gajx3g0j2zp63nhjj2c07g16885vxv4ykwnrfmzbgk4w";
    };
  }
  {
    goPackagePath = "github.com/nsf/termbox-go";
    fetch = {
      type = "git";
      url = "https://github.com/nsf/termbox-go";
      rev = "0938b5187e61bb8c4dcac2b0a9cf4047d83784fc";
      sha256 = "02giav06jd9c3nczylq1vxpp1yyr2xqjyrkiqz37nmb013hjaxli";
    };
  }
]
